require("halfdark").setup()

-- terminal colors

-- local bg = palette.bg0
-- local fg = palette.fg
-- local punct_fg = palette.grey
-- local def_fg = palette.blue
-- local const_fg = palette.blue
-- local active = "#cd974b"
-- local string_fg = palette.green
-- local darker_fg = "#7d7d7d"
-- local diffadd = "#6abf40"
-- local diffdelete = "#d2322d"
-- local diffchange = "#ec8013"
-- local statusline = "#162022"
-- local comment = palette.grey
-- local dim_comment = "#696969"
-- local mistake = {
--     fg = "#c33c33",
--     bg = "#2b1d1e",
-- }
-- local error = "#d13e23"
-- local warn = "#f4b371"
-- local hint = "#8ebeec"
-- local info = "#88cc66"
-- local comment_fg = vim.g.alabaster_dim_comments and dim_comment or comment
-- local comment_bg = palette.bg_d
-- local pmenu_bg = "#182325"
-- local float_bg = vim.g.alabaster_floatborder and bg or pmenu_bg
-- local floatborder = vim.g.alabaster_floatborder and { bg = bg, fg = "#333333" }
--     or {
--         bg = float_bg,
--         fg = float_bg,
--     }
-- local theme = {
--     Cursor = { bg = fg, fg = bg },
--     -- lCursor      { }, -- the character under the cursor when |language-mapping| is used (see 'guicursor')
--     -- CursorIM     { }, -- like Cursor, but used when in IME mode |CursorIM|
--     Directory = { fg = palette.blue },
--     DiffAdd = { bg = "#244032", fg = "#56d364" },
--     DiffDelete = { bg = "#462c32", fg = "#f85149" },
--     DiffText = { fg = "#341a00", bg = "#fff987" },
--     DiffChange = { bg = "#341a00", fg = "#e3b341" },
--     EndOfBuffer = { fg = "#354c50" },
--     -- TermCursor   { }, -- cursor in a focused terminal
--     TermCursorNC = { fg = bg, bg = fg },
--     ErrorMsg = { fg = error, bg = mistake.bg },
--     VertSplit = { fg = "#2b3d40" },
--     Folded = { bg = "#182325", fg = "#7d7d7d" },
--     FoldColumn = { bg = bg, fg = "#4d4d4d" },
--     SignColumn = {},
--     IncSearch = { bg = palette.yellow, fg = bg },
--     -- Substitute   { }, -- |:substitute| replacement text highlighting
--     LineNr = { fg = "#5c5c5c" },
--     CursorLineNr = { fg = palette.blue, bold = 1 },
--     -- MatchParen = { sp = active, bg = palette.bg_d, fg = palette.fg_bright },
--     MatchParen = { bg = palette.light_grey, fg = bg },
--     -- ModeMsg      { }, -- 'showmode' message (e.g., "-- INSERT -- ")
--     -- MsgArea      { }, -- Area for messages and cmdline
--     -- MsgSeparator { }, -- Separator for scrolled messages, `msgsep` flag of 'display'
--     MoreMsg = { fg = palette.green, bold = 1 },
--     NonText = { fg = "#696969" },
--     NormalFloat = { bg = float_bg },
--     -- NormalNC     { }, -- normal text in non-current windows
--     FloatBorder = floatborder,
--     Pmenu = { bg = pmenu_bg },
--     PmenuSel = { bg = "#354c50" },
--     PmenuSbar = { bg = "#212f31" },
--     PmenuThumb = { bg = "#47666b" },
--     Question = { fg = diffadd },
--     QuickFixLine = { bg = "#182325" },
--     Search = { bg = "#354c50" },
--     SpecialKey = { fg = palette.cyan },
--     SpellBad = { undercurl = 1, sp = palette.red },
--     SpellCap = { undercurl = 1, sp = palette.blue },
--     SpellLocal = { undercurl = 1, sp = palette.cyan },
--     SpellRare = { undercurl = 1, sp = palette.magenta },
--     StatusLine = { bg = statusline, fg = fg },
--     StatusLineNC = { bg = statusline, fg = "#9f9f9f" },
--     TabLine = { bg = statusline, fg = "#7d7d7d" },
--     TabLineFill = { bg = statusline },
--     TabLineSel = { bg = statusline, fg = palette.blue },
--     Title = { fg = const_fg },
--     Visual = { bg = "#293334" },
--     VisualNOS = { bg = "#293334" },
--     WarningMsg = { fg = "#e1ad4c" },
--     WildMenu = { bg = "#354c50" },
--     WinBar = { bg = bg, fg = palette.fg, bold = true },
--     WinBarNC = { bg = bg, fg = "#7d7d7d" },
--
--     --- SYNTAX I: TS groups link to these
--
--     --- SYNTAX II: TS groups have their own definition, the below are defined to have somewhat working hl w/o treesitter
--     Identifier = { fg = palette.fg },
--     Function = { fg = def_fg },
--     Statement = { fg = palette.fg },
--     Conditional = { fg = palette.fg },
--     Repeat = { fg = palette.fg },
--     Label = { fg = def_fg },
--     Keyword = { fg = palette.fg },
--     Exception = { fg = palette.fg },
--     PreProc = { fg = palette.fg },
--     Include = { fg = palette.fg },
--     Define = { fg = palette.fg },
--     Macro = { fg = palette.fg },
--     PreCondit = { fg = palette.fg },
--     Type = { fg = palette.fg },
--     StorageClass = { fg = palette.fg },
--     Structure = { fg = def_fg },
--     Typedef = { fg = def_fg },
--
--     Special = { fg = palette.yellow },
--     -- TODO better color than diffchange, try reddish
--     -- SpecialChar = { fg = diffchange }, --  special character in a constant
--     -- Tag            { }, --    you can use CTRL-] on this
--     -- Delimiter      { },
--     SpecialComment = { bg = "#1d292b", fg = palette.blue },
--     debugPc = { bg = "#0f2534" },
--     debugBreakpoint = { bg = "#b33229" },
--     helpHyperTextJump = { fg = palette.magenta },
--     helpSectionDelim = { fg = palette.magenta },
--     helpExample = { fg = palette.cyan },
--     helpCommand = { fg = palette.cyan },
--     helpHeadline = { fg = palette.blue },
--     helpHeader = { fg = palette.magenta },
--
--     Underlined = { underline = 1 }, -- (preferred) text that stands out, HTML links
--     Italic = { italic = 1 },
--
--     -- ("Ignore", below, may be invisible...)
--     -- Ignore         { }, -- (preferred) left blank, hidden  |hl-Ignore|
--
--     Error = { bg = mistake.bg, fg = mistake.fg },
--
--     Todo = { bg = "#d0d058", fg = bg },
--
--     --- Diagnostic
--     LspReferenceText = { underline = 1 },
--     LspReferenceRead = { underline = 1 },
--     LspReferenceWrite = { underline = 1 },
--     LspCodeLens = { fg = "#5c5c5c" },
--     LspCodeLensSeparator = { fg = "#5c5c5c" },
--
--     --- Diagnostic
--     DiagnosticError = { fg = error },
--     DiagnosticWarn = { fg = warn },
--     DiagnosticHint = { fg = hint },
--     DiagnosticInfo = { fg = info },
--     DiagnosticVirtualTextError = { bg = palette.dark_red, fg = error },
--     DiagnosticVirtualTextWarn = { bg = "#3F240A", fg = "#C8935D" },
--     DiagnosticVirtualTextHint = { bg = "#1D2B37", fg = "#7E9CB9" },
--     DiagnosticVirtualTextInfo = { bg = "#162C0B", fg = "#7BAC62" },
--     DiagnosticUnderlineError = { bg = palette.dark_red, fg = palette.fg_bright },
--     DiagnosticUnderlineWarn = { bg = bg, fg = fg, underline = 1, sp = palette.yellow },
--     DiagnosticUnderlineHint = { bg = bg, fg  = fg, underline = 1, sp = palette.blue },
--     DiagnosticUnnecessary = { bg = bg, fg = fg },
--
--     --- Treesitter
--     TSAttribute = {},
--     TSConstructor = { fg = palette.fg },
--     TSConditional = { fg = palette.fg },
--     TSConstBuiltin = { fg = const_fg },
--     TSConstMacro = { fg = palette.fg },
--     TSError = { bg = mistake.bg, fg = mistake.fg },
--     TSException = { fg = palette.fg },
--     TSField = { fg = palette.fg },
--     TSFunction = { fg = palette.fg },
--     TSFuncBuiltin = { fg = palette.fg },
--     TSFuncMacro = { fg = palette.fg },
--     TSKeyword = { fg = palette.fg },
--     TSKeywordFunction = { fg = palette.fg },
--     TSLabel = { fg = palette.fg },
--     TSMethod = { fg = palette.fg },
--     TSNamespace = { fg = palette.fg },
--     TSNone = { fg = const_fg },
--     TSParameter = { fg = palette.fg },
--     TSParameterReference = { fg = palette.fg },
--     TSProperty = { fg = palette.fg },
--     TSPunctDelimiter = { fg = punct_fg },
--     TSPunctBracket = { fg = "#bababa" },
--     TSPunctSpecial = { fg = punct_fg },
--     TSRepeat = { fg = palette.fg },
--     TSString = { fg = string_fg },
--     TSStringRegex = { bg = "#1d292b", fg = const_fg },
--     TSStringEscape = { bg = "#1d292b", fg = const_fg },
--     TSSymbol = {},
--     TSType = { fg = palette.fg },
--     TSTypeBuiltin = { fg = palette.fg },
--     TSVariable = { fg = palette.fg },
--     TSVariableBuiltin = { fg = palette.fg },
--     TSTag = { fg = palette.fg },
--     TSTagDelimiter = { fg = punct_fg },
--     TSText = { fg = palette.fg },
--     ["@attribute"] = {},
--     ["@constructor"] = { fg = palette.fg },
--     ["@conditional"] = { fg = palette.fg },
--     ["@constant.builtin"] = { fg = const_fg },
--     ["@constant.macro"] = { fg = palette.fg },
--     ["@error"] = { bg = mistake.bg, fg = mistake.fg },
--     ["@exception"] = { fg = palette.fg },
--     ["@field"] = { fg = palette.fg },
--     ["@function"] = { fg = def_fg },
--     ["@function.builtin"] = { fg = palette.fg },
--     ["@function.macro"] = { fg = palette.fg },
--     ["@keyword"] = { fg = palette.fg },
--     ["@keyword.function"] = { fg = palette.fg },
--     ["@keyword.operator"] = { fg = punct_fg },
--     ["@label"] = { fg = palette.fg },
--     ["@markup.raw.markdown_inline"] = { link = "String" },
--     ["@method"] = { fg = palette.fg },
--     ["@module"] = { fg = palette.fg },
--     ["@namespace"] = { fg = palette.fg },
--     ["@none"] = { fg = const_fg },
--     ["@parameter"] = { fg = palette.fg },
--     ["@parameter.reference"] = { fg = palette.fg },
--     ["@property"] = { fg = palette.fg },
--     ["@punctuation.delimiter"] = { fg = punct_fg },
--     ["@punctuation.bracket"] = { fg = punct_fg },
--     ["@punctuation.special"] = { fg = punct_fg },
--     ["@repeat"] = { fg = palette.fg },
--     ["@string"] = { fg = string_fg },
--     ["@string.regex"] = { bg = "#1d292b", fg = const_fg },
--     ["@string.escape"] = { bg = "#1d292b", fg = const_fg },
--     ["@symbol"] = {},
--     ["@type"] = { fg = palette.fg },
--     ["@type.builtin"] = { fg = palette.fg },
--     ["@variable"] = { fg = palette.fg },
--     ["@variable.builtin"] = { fg = palette.fg },
--     ["@tag"] = { fg = palette.fg },
--     ["@tag.delimiter"] = { fg = punct_fg },
--     ["@text"] = { fg = palette.fg },
--     ["@text.note"] = { bg = "#1d292b", fg = palette.blue },
--     ["@text.warning"] = { bg = "#d0d058", fg = bg },
--
--     --- Theme specific
--     ["@AlabasterBase"] = { fg = palette.fg },
--     ["@AlabasterConstant"] = { fg = const_fg },
--     ["@AlabasterDefinition"] = { fg = def_fg },
--     ["@AlabasterPunct"] = { fg = punct_fg },
--     ["@AlabasterString"] = { fg = string_fg },
--     ["@AlabasterHashbang"] = { fg = dim_comment },
--     --- Gitsigns
--     GitSignsAdd = { fg = diffadd },
--     GitSignsChange = { fg = diffchange },
--     GitSignsDelete = { fg = diffdelete },
--     --- Telescope
--     TelescopeBorder = { fg = "#2b3d40" },
--     TelescopeMatching = { fg = "#f09942" },
--     TelescopeMultiSelection = { fg = palette.magenta },
--     TelescopePromptPrefix = { fg = palette.blue },
--     TelescopeSelectionCaret = { fg = mistake.fg },
--     TelescopeTitle = { fg = palette.brightyellow },
--     TelescopeResultsTitle = { fg = palette.yellow },
--     --- fzf-lua
--     FzfLuaBorder = { fg = "#2b3d40" },
--     --- Neogit
--     NeogitPopupActionDisabled = { fg = darker_fg },
--     NeogitPopupActionKey = { fg = palette.magenta },
--     NeogitPopupOptionDisabled = { fg = darker_fg },
--     NeogitPopupOptionKey = { fg = palette.blue },
--     NeogitPopupSwitchDisabled = { fg = darker_fg },
--     NeogitPopupSwitchEnabled = { fg = palette.cyan },
--     NeogitPopupSwitchKey = { fg = palette.magenta },
--     --- Fugitive
--     diffAdded = { link = "DiffAdd" },
--     diffRemoved = { link = "DiffDelete" },
--     --- Startify
--     StartifyBracket = { fg = darker_fg },
--     StartifyFile = { fg = palette.fg },
--     StartifySection = { fg = palette.green },
--     StartifySlash = { fg = "#4e6e75" },
--     StartifyPath = { fg = "#4e6e75" },
--     --- Statusline
--     StatuslineAdd = { fg = diffadd, bg = statusline },
--     StatuslineErr = { fg = error, bg = statusline },
--     StatuslineHint = { fg = hint, bg = statusline },
--     StatuslineInfo = { fg = info, bg = statusline },
--     StatuslineWarn = { fg = warn, bg = statusline },
--     StatuslineBlue = { fg = palette.blue, bg = statusline },
--     StatuslineRed = { fg = palette.red, bg = statusline },
--     StatuslineGreen = { fg = palette.green, bg = statusline },
--     StatuslineCyan = { fg = palette.cyan, bg = statusline },
--     StatuslineMagenta = { fg = palette.magenta, bg = statusline },
--     --- ALE
--     ALEWarningSign = { fg = warn },
--     --- vim-matchup
--     MatchupVirtualText = { fg = palette.yellow },
--     --- For `highlight link`
--     AlabasterBlack = { fg = palette.black },
--     AlabasterBlue = { fg = palette.blue },
--     AlabasterBrightYellow = { fg = palette.brightyellow },
--     AlabasterCyan = { fg = palette.cyan },
--     AlabasterGreen = { fg = palette.green },
--     AlabasterDarkGreen = { fg = "#6abf40" },
--     AlabasterMagenta = { fg = palette.magenta },
--     AlabasterRed = { fg = palette.red },
--     AlabasterWhite = { fg = palette.fg },
--     AlabasterYellow = { fg = palette.yellow },
--     --- Hop
--     HopNextKey = { fg = palette.brightyellow },
--     HopNextKey1 = { fg = palette.cyan },
--     HopNextKey2 = { fg = "#297567" },
--     HopUnmatched = { fg = "#3d3d3d" },
--     --- Lightspeed
--     LightspeedGreyWash = { fg = "#3d3d3d" },
--     --- checkhealth
--     healthSuccess = { fg = palette.green, bg = bg },
--     --- cmp
--     CmpItemMenuDefault = { fg = palette.magenta },
--     --- nvim-ts-rainbow
--     rainbowcol1 = { fg = palette.yellow },
--     rainbowcol2 = { fg = palette.magenta },
--     rainbowcol3 = { fg = palette.blue },
--     rainbowcol4 = { fg = palette.green },
--     rainbowcol5 = { fg = palette.brightyellow },
--     rainbowcol6 = { fg = palette.red },
--     rainbowcol7 = { fg = palette.cyan },
--     --- Iswap
--     ISwapSnipe = { bg = palette.yellow, fg = bg },
--     ISwapGrey = { fg = "#3d3d3d" },
--     --- vim-dadbod-ui
--     dbui_help = { fg = dim_comment },
--     dbui_connection_source = { fg = dim_comment },
--     --- nvim-dap-virtual-text
--     NvimDapVirtualText = { bg = "#1d292b", fg = palette.cyan },
--     --- Noice
--     NoiceCmdlineIcon = { link = "AlabasterDarkGreen" },
--     NoiceCmdlinePopupBorder = { link = "AlabasterDarkGreen" },
--     NoiceConfirmBorder = { link = "AlabasterDarkGreen" },
--     NoiceCmdlinePopupBorderCmdline = { link = "AlabasterDarkGreen" },
--     NoiceCmdlineIconCmdline = { link = "AlabasterDarkGreen" },
--     NoiceCmdlinePopupBorderFilter = { link = "AlabasterDarkGreen" },
--     NoiceCmdlineIconFilter = { link = "AlabasterDarkGreen" },
--     NoiceCmdlinePopupBorderLua = { link = "AlabasterDarkGreen" },
--     NoiceCmdlineIconLua = { link = "AlabasterDarkGreen" },
--     NoiceCmdlinePopupBorderSearch = { link = "AlabasterYellow" },
--     NoiceCmdlineIconSearch = { link = "AlabasterYellow" },
--     -- Languages
--     --- asm
--     asmDirective = { fg = dim_comment },
--     nasmLabel = { link = "@AlabasterDefinition" },
-- }
